### ISSUE TITLE
Global, 전역 스타일 정의와 다크모드를 구현하여 스타일 적용의 효율성과 사용성을 높인다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#1]
## Task
전역 스타일 정의와 다크모드를 구현한다.

## Subtask ListUp
- [x] sass 최상단 스타일링 추가
- [x] 스타일 전역 변수 정의
- [x] sass 라이트 모드 스타일링 추가
- [x] sass 다크 모드 스타일링 추가
- [x] 토글 버튼 구현
- [x] 토글 기능 훅 구현
- [x] 개발 로그 README 업데이트
