### ISSUE TITLE
Registration, 유저 등록 시 github oauth로 이루어질 수 있도록 강화한다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#13]
## Task
유저 등록 시 github oauth로 이루어질 수 있도록 강화한다.

## Subtask ListUp
- [ ] registration에서 구성해둔 컴포넌트가 필요할까?
- [ ] 필요없다면, 제거하고 oauth로 대체하자.
- [ ] 전역적인 유저 정보를 위해 입력받은 userId는 access_token을 전달받을 때 응답으로 함께 처리할 수 있지는 않을까?
- [ ] 가만 보니까, access_token 구하는 유틸을 그냥 registration으로 옮겨도 되겠다. 대신 그 토큰 만료됐을 때 다시 registration으로 돌아가는 플로우가 좋을 까 싶다.
