### ISSUE TITLE
Language, 사용한 언어에 대한 통계를 확인할 수 있다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#14]
## Task
사용한 언어에 대한 통계를 확인할 수 있다.

## Subtask ListUp
- [ ] language 섹션을 만들어서, 사용언어에 대한 기록을 남기고 싶은데, 어떻게 보여줘야 예쁠지 고민
- [ ] 사실, 정말로 필요로 하는 기능인지 아니면 신기해서 한번보고 말것같은 기능인지는 판단이 필요
- [ ] 가장 많이 사용하는 언어만 예쁘게 보여줘도 나쁘진 않겠다.
