### ISSUE TITLE
Global, 전역 색상값과 그리드 레이아웃을 구축한다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#15]
## Task
전역 색상값과 그리드 레이아웃을 구축한다.

## Subtask ListUp
- [ ] 전역 색상값 아무리봐도 바꾸긴 해야할 것 같다. 애플 홈페이지에서 사용되는 다크 색상 가져다 쓰자..
- [ ] 전역 그리드 레이아웃을 구축해야 한다. language 섹션이 추가되고, 어느정도 반응형으로 구현이 필요한 단계
- [ ] 사이즈도 rem으로 통일할 것인지, 그렇지 못한 px 값들은 어떻게 처리할 수 있을 지 고민 필요
