### ISSUE TITLE
Global, feature-based 프로젝트 구조 자동 구축을 통해 작업의 효율성을 높일 수 있다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#2]
## Task
feature-based 프로젝트 구조를 담은 hygen 폼과 스크립트를 생성한다.

## Subtask ListUp
- [ ] hygen 의존성 추가
- [ ] feature-based 구조화된 파일 생성을 위한 hygen 폼 생성
- [ ] feature-based 파일, 폴더 생성을 위한 스크립트 추가
