### ISSUE TITLE
Global, axios, react-query를 통해 API 환경을 구축한다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#3]
## Task
axios, react-query를 통해 API 환경을 구축한다.

## Subtask ListUp
- [x] axios, react-query 의존성 추가
- [x] axios base instance 정의
- [x] react-query 전역 환경 구축
