### ISSUE TITLE
User, 깃헙 유저 프로필을 확인할 수 있다.

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#6]
## Task
깃헙 유저 프로필을 확인할 수 있다.

## Subtask ListUp
- [ ] 초기 사용자 설정
- [ ] user 아이디 설정을 위한 글로벌 컨텍스트 생성
- [ ] user section feature 구현
