### ISSUE TITLE
User, 테스트 코드 작성, API 인터페이스 정의 필요

### ISSUE THREAD

**Issue by youthfulhps** [youthfulhps-tutorial/github-electron#9]
## Task
유저 프로필 기능 개발에서 마무리하지 못한 테스트 코드와 API 인터페이스를 정의한다.

## Subtask ListUp
- [ ] OAG를 통한 API, 인터페이스 정의
- [ ] 인터페이스, API 인터페이스 정의
- [ ] Mock 데이터 정의
- [ ] UserProfile, Registration 테스트 코드 작성
